vich_uploader:
    db_driver: orm

    mappings:
        product_image:
            uri_prefix: ../../dist/img/system
            upload_destination: '%kernel.project_dir%/public/dist/img/system'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: false
            delete_on_update: false
            delete_on_remove: true